#!/usr/bin/env python3
"""Apply the Jw16AneVa dart_fw_map patch v2 (default-domain fixed-IOVA maps)."""
import sys

src = sys.argv[1]
s = open(src).read()
BS = chr(92)
CRLF = BS + "n"
T = chr(9)

BLOCK = (
    "\n/*\n"
    " * Jw16AneVa dart_fw_map (TEST BUILD, window-only): map the eos firmware\n"
    " * segments at the fixed ADT iova fields through the kernel apple-dart\n"
    " * driver, INTO THE DEVICE'S OWN DEFAULT DOMAIN (no domain swap, no raw\n"
    " * dart MMIO), gated by a read-only live-carveout proof. Inert unless\n"
    " * dart_fw_map=1 with all params given.\n"
    " */\n"
    "static bool dart_fw_map;\n"
    "module_param(dart_fw_map, bool, 0444);\n"
    "static unsigned long long fw_text_pa, fw_text_size = 0xd4000ULL;\n"
    "static unsigned long long fw_data_pa, fw_data_size = 0x438000ULL;\n"
    "static unsigned long long fw_expect_a, fw_expect_b;\n"
    "module_param(fw_text_pa, ullong, 0444);\n"
    "module_param(fw_text_size, ullong, 0444);\n"
    "module_param(fw_data_pa, ullong, 0444);\n"
    "module_param(fw_data_size, ullong, 0444);\n"
    "module_param(fw_expect_a, ullong, 0444);\n"
    "module_param(fw_expect_b, ullong, 0444);\n"
    "\n"
    "static struct iommu_domain *fw_map_domain;\n"
    "static size_t fw_mapped_text, fw_mapped_data;\n"
    "\n"
    "static void ane_fw_span_fletcher(const void *p, size_t len, size_t skip_off,\n"
    "\t\t\t\t u64 *fa, u64 *fb)\n"
    "{\n"
    "\tconst __le32 *w = p;\n"
    "\tsize_t i;\n"
    "\n"
    "\t*fa = *fb = 0;\n"
    "\tfor (i = 0; i < len / 4; i++) {\n"
    "\t\tu32 v;\n"
    "\n"
    "\t\tif (i * 4 == skip_off)\n"
    "\t\t\tcontinue;\n"
    "\t\tv = le32_to_cpu(w[i]);\n"
    "\t\t*fa += v;\n"
    "\t\t*fb += *fa;\n"
    "\t}\n"
    "}\n"
    "\n"
    "static void ane_dart_fw_map_detach(struct ane_device *ane)\n"
    "{\n"
    "\tif (!fw_map_domain)\n"
    "\t\treturn;\n"
    "\tif (fw_mapped_data)\n"
    "\t\tiommu_unmap(fw_map_domain, fw_mapped_text, fw_mapped_data);\n"
    "\tif (fw_mapped_text)\n"
    "\t\tiommu_unmap(fw_map_domain, 0, fw_mapped_text);\n"
    "\tfw_map_domain = NULL;\n"
    "\tfw_mapped_text = fw_mapped_data = 0;\n"
    "\tdev_info(ane->dev, \"dart_fw_map: unmapped; default domain intact" + CRLF + "\");\n"
    "}\n"
    "\n"
    "static int ane_dart_fw_map(struct ane_device *ane)\n"
    "{\n"
    "\tstruct iommu_domain *dom;\n"
    "\tvoid *tv, *dv;\n"
    "\tvoid __iomem *ti;\n"
    "\tu64 fa, fb, va, vb, ua, ub;\n"
    "\tu32 nz = 0, i;\n"
    "\tphys_addr_t chk;\n"
    "\tint ret;\n"
    "\n"
    "\tif (!fw_text_pa || !fw_data_pa || !fw_expect_a || !fw_expect_b) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: params missing" + CRLF + "\");\n"
    "\t\treturn -EINVAL;\n"
    "\t}\n"
    "\n"
    "\t/* live proof 1a: TEXT head in two independent views must agree */\n"
    "\ttv = memremap(fw_text_pa, 0x400, MEMREMAP_WC);\n"
    "\tif (!tv) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: memremap TEXT failed" + CRLF + "\");\n"
    "\t\treturn -ENOMEM;\n"
    "\t}\n"
    "\tane_fw_span_fletcher(tv, 0x400, 0x200, &va, &vb);\n"
    "\tmemunmap(tv);\n"
    "\tti = ioremap(fw_text_pa, 0x400);\n"
    "\tif (!ti) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: ioremap TEXT failed" + CRLF + "\");\n"
    "\t\treturn -ENOMEM;\n"
    "\t}\n"
    "\tua = ub = 0;\n"
    "\tfor (i = 0; i < 0x400 / 4; i++) {\n"
    "\t\tu32 v = readl(ti + i * 4);\n"
    "\n"
    "\t\tif (i * 4 == 0x200)\n"
    "\t\t\tcontinue;\n"
    "\t\tua += v;\n"
    "\t\tub += ua;\n"
    "\t}\n"
    "\tiounmap(ti);\n"
    "\tif (ua != va || ub != vb) {\n"
    "\t\tdev_err(ane->dev,\n"
    "\t\t\t\"dart_fw_map: TEXT view mismatch (%016llx:%016llx vs %016llx:%016llx) - no map, no release" + CRLF + "\",\n"
    "\t\t\tua, ub, va, vb);\n"
    "\t\treturn -EKEYREJECTED;\n"
    "\t}\n"
    "\n"
    "\t/* live proof 1b: full head digest vs the pinned 22G74 reference */\n"
    "\ttv = memremap(fw_text_pa, fw_text_size, MEMREMAP_WC);\n"
    "\tif (!tv) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: memremap TEXT failed" + CRLF + "\");\n"
    "\t\treturn -ENOMEM;\n"
    "\t}\n"
    "\tane_fw_span_fletcher(tv, 0x8000, 0x200, &fa, &fb);\n"
    "\tmemunmap(tv);\n"
    "\tdev_info(ane->dev,\n"
    "\t\t \"dart_fw_map: TEXT live fletcher %016llx:%016llx (want %016llx:%016llx)" + CRLF + "\",\n"
    "\t\t fa, fb, fw_expect_a, fw_expect_b);\n"
    "\tif (fa != fw_expect_a || fb != fw_expect_b) {\n"
    "\t\tdev_err(ane->dev,\n"
    "\t\t\t\"dart_fw_map: TEXT PROOF FAILED - no map, no release" + CRLF + "\");\n"
    "\t\treturn -EKEYREJECTED;\n"
    "\t}\n"
    "\n"
    "\t/* live proof 2: DATA carveout head must read zero pre-staging */\n"
    "\tdv = memremap(fw_data_pa, 0x1000, MEMREMAP_WC);\n"
    "\tif (!dv) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: memremap DATA failed" + CRLF + "\");\n"
    "\t\treturn -ENOMEM;\n"
    "\t}\n"
    "\tfor (i = 0; i < 0x1000 / 4; i++) {\n"
    "\t\tu32 v = *((volatile u32 *)(dv + i * 4));\n"
    "\n"
    "\t\tif (v)\n"
    "\t\t\tnz++;\n"
    "\t}\n"
    "\tmemunmap(dv);\n"
    "\tdev_info(ane->dev, \"dart_fw_map: DATA head nonzero words: %u/1024" + CRLF + "\",\n"
    "\t\t nz);\n"
    "\tif (nz) {\n"
    "\t\tdev_err(ane->dev,\n"
    "\t\t\t\"dart_fw_map: DATA PA not a fresh carveout - no map, no release" + CRLF + "\");\n"
    "\t\treturn -EKEYREJECTED;\n"
    "\t}\n"
    "\n"
    "\tdom = iommu_get_domain_for_dev(ane->dev);\n"
    "\tif (!dom) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: no iommu domain\\n\");\n"
    "\t\treturn -ENODEV;\n"
    "\t}\n"
    "\tret = iommu_map(dom, 0, fw_text_pa, fw_text_size,\n"
    "\t\t\tIOMMU_READ | IOMMU_WRITE | IOMMU_CACHE, GFP_KERNEL);\n"
    "\tif (ret) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: TEXT map failed %d\\n\", ret);\n"
    "\t\treturn ret;\n"
    "\t}\n"
    "\tret = iommu_map(dom, fw_text_size, fw_data_pa, fw_data_size,\n"
    "\t\t\tIOMMU_READ | IOMMU_WRITE | IOMMU_CACHE, GFP_KERNEL);\n"
    "\tif (ret) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: DATA map failed %d\\n\", ret);\n"
    "\t\tiommu_unmap(dom, 0, fw_text_size);\n"
    "\t\treturn ret;\n"
    "\t}\n"
    "\tfw_map_domain = dom;\n"
    "\tfw_mapped_text = fw_text_size;\n"
    "\tfw_mapped_data = fw_data_size;\n"
    "\tchk = iommu_iova_to_phys(dom, 0);\n"
    "\tif (chk != fw_text_pa) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: iova0 readback %pap" + CRLF + "\", &chk);\n"
    "\t\tane_dart_fw_map_detach(ane);\n"
    "\t\treturn -EIO;\n"
    "\t}\n"
    "\tchk = iommu_iova_to_phys(dom, fw_text_size);\n"
    "\tif (chk != fw_data_pa) {\n"
    "\t\tdev_err(ane->dev, \"dart_fw_map: DATA iova readback %pap" + CRLF + "\",\n"
    "\t\t\t&chk);\n"
    "\t\tane_dart_fw_map_detach(ane);\n"
    "\t\treturn -EIO;\n"
    "\t}\n"
    "\tdev_info(ane->dev,\n"
    "\t\t \"dart_fw_map: MAPPED into default domain - TEXT iova 0 size 0x%llx pa 0x%llx; DATA iova 0x%llx size 0x%llx pa 0x%llx" + CRLF + "\",\n"
    "\t\t fw_text_size, fw_text_pa, fw_text_size, fw_data_size,\n"
    "\t\t fw_data_pa);\n"
    "\treturn 0;\n"
    "}\n"
    "\n"
)

if "dart_fw_map" in s:
    print("already patched")
    sys.exit(0)

anchor1 = "#define CMD_BUF_BDX 0"
assert s.count(anchor1) == 1, "anchor1"
s = s.replace(anchor1, BLOCK + anchor1)

anchor2 = T + 'dev_info(dev, "loaded ane' + CRLF + '");' + "\n\n" + T + "return 0;"
assert s.count(anchor2) == 1, "anchor2"
s = s.replace(
    anchor2,
    T + "if (dart_fw_map) {\n"
    + T + T + "err = ane_dart_fw_map(ane);\n"
    + T + T + "if (err) {\n"
    + T + T + T + "drm_dev_unregister(drm);\n"
    + T + T + T + "goto put_pm;\n"
    + T + T + "}\n"
    + T + "}\n\n"
    + anchor2,
)

anchor3 = T + "struct ane_bo *bo, *tmp;\n\n" + T + "mutex_lock(&ane->engine_lock);"
assert s.count(anchor3) == 1, "anchor3"
s = s.replace(
    anchor3,
    T + "struct ane_bo *bo, *tmp;\n\n"
    + T + "ane_dart_fw_map_detach(ane);\n"
    + T + "mutex_lock(&ane->engine_lock);",
)

open(src, "w").write(s)
print("patched OK")
